# Setup
title:               Junseok Lee
tagline:             'homepage'
description:         'Personal homepage about Junseok Lee'
url:                 https://junseok0207.github.io./
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Junseok Lee
  url:               https://twitter.com/ljs960207
  email:             junseoklee@kaist.ac.kr

gravatar_md5: a0c647f2ce4de17d7cbd23173fc0e7e8

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
